rootProject.name = "qrforge4j"
include("qrgen-core")
include("qrgen-svg") 
include("qrgen-png")
include("qrgen-pdf")
include("qrgen-dsl")
include("qrgen-test")
include("qrgen-cli")
include("qrgen-ktor")
include("qrgen-spring-boot-starter")
include("qrgen-batch")
include("qrgen-micronaut")
